# List of dependecies for CSI attacher

[[constraint]]
  name = "github.com/container-storage-interface/spec"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-test"
  version = "v1.0.0-1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.9.2"

[[override]]
  name = "github.com/json-iterator/go"
  version = "1.1.4"

# TODO: use [[constraint]] when kubernetes-csi/kubernetes-csi-migration-library uses 1.13 code
[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.0-beta.2"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.0-beta.2"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.0-beta.2"


[[override]]
  name = "k8s.io/csi-api"
  version = "kubernetes-1.13.0-beta.2"

[[constraint]]
  name = "github.com/kubernetes-csi/csi-lib-utils"
  version = "0.1.0"

[prune]
   non-go = true
   go-tests = true
   unused-packages = true

